config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :deliveries
  resources :availabilities
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  get '/users/fetch_users', to: 'users#fetch_users'
  resources :users
  resources :branches do
    get :join_company, on: :collection
  end
  resources :companies
  #resources :articles

  devise_scope :user do
    get 'choose_branch', to: 'devise/sessions#choose_branch'
  end

  root "home#home"

  get '/dashboard', to: 'dashboard#index', as: 'user_dashboard'
  get 'join_company', to: 'companies#join'

  get 'join_request/:company_id', to: 'companies#join_request', as: 'join_request'
  get 'join_now/:company_id', to: 'companies#join_now', as: 'join_now'

  get 'select_branch/:branch_id', to: 'branches#select_branch', as: 'select_branch'

  get '/contact', to: 'contact_customer#show_form', as: 'contact_form'
  post '/contact', to: 'contact_customer#send_email', as: 'send_contact'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    # Add any code here to display data on the dashboard
    #if current_user.branch_id.nil?
    #  @joined_company = false
    #end
  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<% if joined_company %>
  <div class="container mt-4">
    <h1 class="text-center">
      Welcome to your dashboard, <%= current_user.email %>
    </h1>
    <!-- Add any code here to display data on the dashboard -->
    <% if current_user.role == "admin" %>
        <div class="card">
            <div class="card-body">
                <h3>Quick Guide</h3>
                <p>Welcome to Routes! Here's a quick guide to get started as a manager:</p>
                <ul>
                    <li>Schedule: View branch and user schedules in a friendly calendar view.</li>
                    <li>Deliveries: Create new deliveries for your branch here. Also, if you have deliveries assinged to you, they can be seen here in a table view.</li>
                    <li>Add Availability: Add new availability to allow other branch managers to assign deliveries to you.</li>
                    <li>Company: See your company info here.</li>
                    <li>Branches: See the company branches and their info here.</li>
                    <li>User: View all users within the company and info about them here. You can also assign user roles and branches here too.</li>
                    <li>Profile: Update your login and account info here!</li>
                </ul>
            </div>
        </div>
    <% end %>
    <% if current_user.role == "driver" %>
        <div class="card mt-3">
            <div class="card-body">
                <h3>Quick Guide</h3>
                <p>Welcome to Routes! Here's a quick guide to get started as a driver:</p>
                <ul>
                    <li>Schedule: View your schedule of deliveries in a friendly calendar view.</li>
                    <li>Deliveries: If you have deliveries assinged to you, they can also be seen here in a table view.</li>
                    <li>Add Availability: Add new availability to allow branch managers to assign deliveries to you.</li>
                    <li>Company: See your company info here.</li>
                    <li>Branches: See your branches and their info here.</li>
                    <li>User: Info about your user is displayed here.</li>
                    <li>Profile: Update your login and account info here!</li>
                </ul>
            </div>
        </div>
    <% end %>
<% else %>
  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-10">
        <div class="d-flex justify-content-center">
          <%= link_to "Create a Company", new_company_path, class: "btn btn-primary btn-md mb-2" %>
        </div>
        <div class="d-flex justify-content-center">
          <%= link_to "Join a Company", join_company_path, class: "btn btn-primary btn-md mb-2" %>
        </div>
      </div>
    </div>
  </div>
<% end %>