config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :deliveries
  resources :availabilities
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  get '/users/fetch_users', to: 'users#fetch_users'
  resources :users
  resources :branches do
    get :join_company, on: :collection
  end
  resources :companies
  #resources :articles

  devise_scope :user do
    get 'choose_branch', to: 'devise/sessions#choose_branch'
  end

  root "home#home"

  get '/dashboard', to: 'dashboard#index', as: 'user_dashboard'
  get 'join_company', to: 'companies#join'

  get 'join_request/:company_id', to: 'companies#join_request', as: 'join_request'
  get 'join_now/:company_id', to: 'companies#join_now', as: 'join_now'

  get 'select_branch/:branch_id', to: 'branches#select_branch', as: 'select_branch'

  get '/contact', to: 'contact_customer#show_form', as: 'contact_form'
  post '/contact', to: 'contact_customer#send_email', as: 'send_contact'
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :company
  has_many :users, dependent: :destroy
  has_one :schedule, dependent: :destroy
  validates :name, presence: true


  after_create :create_default_schedule

  private
  # Create a new schedule associated with the branch
  def create_default_schedule
    create_schedule(branch_id: id, branch_only: true) 
  end

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_admin_role, only: [:edit, :update, :destroy]

  # GET /branches or /branches.json
  def index
    @branches = current_user.company.branches
  end

  # GET /branches/1 or /branches/1.json
  def show
    @branch = Branch.find(params[:id])

    # Allow showing the branch if it's associated with the current user's branch_id
    # OR if the current user is an admin and the branch is associated with the user's company_id.
    if (@branch.id == current_user.branch_id) || (current_user.role == "admin" && @branch.company_id == current_user.company.id)
      render :show
    else
      redirect_to root_path, alert: "You do not have permission."
    end
  end

  # GET /branches/new
  def new
    unless (current_user.role == "admin")
        redirect_to root_path, alert: "You do not have permission."
        return
    end
    @branch = Branch.new    
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches or /branches.json
  def create
    unless (current_user.role == "admin")
        redirect_to root_path, alert: "You do not have permission."
        return
    end  


    @branch = Branch.new(branch_params)
    #company = Company.find_by(company_iden: params[:branch][:company_iden])
    #@branch.company = company

    #company = Company.find_by(params[:company_id])
    company = current_user.company
    @branch.company = company
    @branch.company_iden = company.company_iden

    unless (@branch.company.id == current_user.branch.company.id)
        redirect_to root_path, alert: "You do not have permission."
        return
    end

    respond_to do |format|
      if @branch.save
        create_schedule_for_branch
        current_user.update(branch_id: @branch.id) if current_user.branch_id.nil?
        format.html { redirect_to branch_url(@branch), notice: "Branch was successfully created." }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1 or /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        company = Company.find_by(company_iden: params[:company_iden])
        @branch.company_id = company.id if company
        format.html { redirect_to branch_url(@branch), notice: "Branch was successfully updated." }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1 or /branches/1.json
  def destroy
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Branch and associated users were successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def join_company
    @company = Company.find(params[:company_id])
    @branches = @company.branches
    render "select_branch"
  end

  def select_branch
      branch = Branch.find(params[:branch_id])
      current_user.update(role: "driver", branch_id: branch.id)
      redirect_to user_dashboard_path, notice: "Branch selected successfully."
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def branch_params
      params.require(:branch).permit(:name, :branch_iden)
    end

    def create_schedule_for_branch
        @branch.create_schedule(branch_id: @branch.id, branch_only: true) 
    end   

    def check_admin_role
        unless (current_user.role == "admin" && @branch.company.id == current_user.branch.company.id)
          redirect_to root_path, alert: "You do not have permission to access this page."
        end
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_branch.html.erb
<div id="<%= dom_id branch %>" class="card my-3">
      <div class="card-body">
        <p class="card-text">
          <strong>Name:</strong>
          <%= branch.name %>
        </p>
      </div>
</div>

app/views/branches/_form.html.erb
<%= form_with(model: branch, class: "form-horizontal") do |form| %>
  <% if branch.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
        <% branch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div style="display: none;">
    <div class="form-group">
      <%= form.label :branch_iden, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= form.text_field :branch_iden, class: "form-control" %>
      </div>
    </div>
  </div>

  <div style="display: none;">
    <div class="form-group">
      <%= form.label :company_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_field_tag :company_iden, form.object.company_iden, class: "form-control", disabled: true, readonly: true %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10 mt-3">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render "form", branch: @branch %>

<br>

<div>
  <%= link_to "Show this branch", @branch %> |
  <%= link_to "Back to branches", branches_path %>
</div>

app/views/branches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Branches</h1>
<% if current_user.role == 'admin' %>
	<%= link_to "New branch", new_branch_path%>
	<br></br>
<% end %>

<div class="container-fluid">
  <div id="branches" class="row">
    <% @branches.each do |branch| %>
      <div class="col-sm-6 col-md-4">
        <div id="<%= dom_id branch %>" class="card my-3">
          <div class="card-body">
            <p class="card-text">
              <strong>Name:</strong>
              <%= branch.name %>
            </p>
            <%= link_to "Show this branch", branch, class: "btn btn-primary btn-sm" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/branches/new.html.erb
<h1>New branch</h1>

<%= render "form", branch: @branch %>

<br>

<div>
  <%= link_to "Back to branches", branches_path %>
</div>

app/views/branches/select_branch.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-4">
    <h1>Select a Branch</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @branches.each do |branch| %>
                <tr>
                    <td>
                        <%= branch.name %>
                    </td>
                    <td>
                        <%= link_to "Select Branch", select_branch_path(branch_id: branch.id), class: "btn btn-primary" %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/branches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @branch %>

<div class="d-flex justify-content-between align-items-center">
	<%= link_to "Edit this branch", edit_branch_path(@branch), class: "btn btn-primary" if current_user.role == "admin"%>
	<%= link_to "Back to branches", branches_path, class: "btn btn-secondary" %>
	<%= button_to "Destroy this branch", @branch, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", form: { class: "d-inline" } if current_user.role == "admin"%>

</div>
<div class="text-center">
	<br></br>
	<% if current_user.role == 'admin' %>
	<p>Warning: Destroying this branch will delete all associated users and deliveries!</p>
	<% end %>
</div>