config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :deliveries
  resources :availabilities
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  get '/users/fetch_users', to: 'users#fetch_users'
  resources :users
  resources :branches do
    get :join_company, on: :collection
  end
  resources :companies
  #resources :articles

  devise_scope :user do
    get 'choose_branch', to: 'devise/sessions#choose_branch'
  end

  root "home#home"

  get '/dashboard', to: 'dashboard#index', as: 'user_dashboard'
  get 'join_company', to: 'companies#join'

  get 'join_request/:company_id', to: 'companies#join_request', as: 'join_request'
  get 'join_now/:company_id', to: 'companies#join_now', as: 'join_now'

  get 'select_branch/:branch_id', to: 'branches#select_branch', as: 'select_branch'

  get '/contact', to: 'contact_customer#show_form', as: 'contact_form'
  post '/contact', to: 'contact_customer#send_email', as: 'send_contact'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :branch, optional: true
  belongs_to :user, optional: true

  has_many :deliveries, dependent: :destroy

  validate :user_or_branch_presence

  private

  def user_or_branch_presence
    errors.add(:base, "Schedule must belong to a user or a branch") unless user.present? || branch.present?
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_admin_role, only: [:show, :destroy]

  # GET /schedules or /schedules.json
  def index
    if current_user.role == 'driver'
      redirect_to schedule_path(current_user.schedule)
    elsif current_user.role == 'admin'
      @schedules = Schedule.where(user_id: current_user.branch.company.users.pluck(:id))
                      .or(Schedule.where(branch_id: current_user.branch.company.branches.pluck(:id)))

      @branch_schedules = Schedule.where(branch_id: current_user.branch.company.branches.pluck(:id))
      @user_schedules = Schedule.where(user_id: current_user.branch.company.users.pluck(:id))
    end
    
  end

  # GET /schedules/1 or /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    if @schedule.user_only && @schedule.user.present?
        @deliveries = @schedule.user.deliveries.joins(schedule: :user).select('deliveries.*, users.email as driver_email')
    elsif @schedule.branch_only && @schedule.branch.present?
        @deliveries = Delivery.joins(schedule: :user)
                          .where('schedules.branch_id = ? OR users.branch_id = ?', @schedule.branch_id, @schedule.branch_id)
                          .select('deliveries.*, users.email as driver_email')
    end
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new

    unless (current_user.role == "admin")
        redirect_to root_path, alert: "You do not have permission."
        return
    end
  end

  # GET /schedules/1/edit
  def edit
    redirect_to root_path, alert: "You do not have permission."

  end

  # POST /schedules or /schedules.json
  def create
    if schedule_params[:user_id].present? # Check if a user is associated with the schedule
      user = User.find(schedule_params[:user_id])
      if user.schedule.present?
        redirect_to new_schedule_path, alert: "User already has an existing schedule."
        return
      end
    end
    
    if schedule_params[:branch_id].present? # Check if a branch is associated with the schedule
      branch = Branch.find(schedule_params[:branch_id])
      if branch.schedule.present?
        redirect_to new_schedule_path, alert: "Branch already has an existing schedule."
        return
      end
    end

    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully created." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def calendar_schedule
      # Retrieve schedules with branches for the current user's company
      @branch_schedules = Schedule.where(branch_only: true, branch_id: current_user.branch.company.schedules.pluck(:id))
                                  .map { |schedule| [schedule.id, schedule.branch.name] }

      # Retrieve schedules with users for the current user's company
      @user_schedules = Schedule.where(user_only: true, user_id: current_user.branch.company.users.pluck(:id))
                                .map { |schedule| [schedule.id, schedule.branch.name] }

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      if params[:id] != "calendar_schedule"
        @schedule = Schedule.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:start_time, :end_time, :branch_id, :user_id, :user_only, :branch_only)
    end

    def check_admin_role
        if(@schedule.user_only == true)
            unless ((current_user.role == "admin" && @schedule.user.branch.company.id == current_user.branch.company.id) || current_user == @schedule.user)
              redirect_to root_path, alert: "You do not have permission."
              return
            end
        end
        if(@schedule.branch_only == true)
            unless ((current_user.role == "admin" && @schedule.branch.company.id == current_user.branch.company.id))
              redirect_to root_path, alert: "You do not have permission."
              return
            end
        end
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule) do |form| %>
  <% if schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :branch_id, style: "display: block" %>
    <%= form.text_field :branch_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :user_only, style: "display: block" %>
    <%= form.check_box :user_only %>
  </div>

  <div>
    <%= form.label :branch_only, style: "display: block" %>
    <%= form.check_box :branch_only %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<div id="<%= dom_id schedule %>">
  <p>
    <strong>Branch:</strong>
    <%= schedule.branch_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= schedule.user_id %>
  </p>

  <p>
    <strong>User only:</strong>
    <%= schedule.user_only %>
  </p>

  <p>
    <strong>Branch only:</strong>
    <%= schedule.branch_only %>
  </p>

</div>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render "form", schedule: @schedule %>

<br>

<div>
  <%= link_to "Show this schedule", @schedule %> |
  <%= link_to "Back to schedules", schedules_path %>
</div>

app/views/schedules/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Schedules</h1>

<div id="schedules", style="display: none;", class="container">
  <% @schedules.each do |schedule| %>
    <%= render schedule %>
    <p>
      <%= link_to "Show this schedule", schedule %>
    </p>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>Branch Schedules</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Branch</th>
            <th>Show</th>
          </tr>
        </thead>
        <tbody>
          <% @branch_schedules.each do |schedule| %>
            <tr>
              <td><%= schedule.branch.name %></td>
              <td><%= link_to "Show", schedule %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <h2>User Schedules</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>User</th>
            <th>Show</th>
          </tr>
        </thead>
        <tbody>
          <% @user_schedules.each do |schedule| %>
            <tr>
              <td><%= schedule.user.email %></td>
              <td><%= link_to "Show", schedule %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render "form", schedule: @schedule %>

<br>

<div>
  <%= link_to "Back to schedules", schedules_path %>
</div>

app/views/schedules/show.html.erb
<p style="color: green"><%= notice %></p>
	
<h2>Schedule of Deliveries</h2>
<div id="schedule-data" data-deliveries="<%= @deliveries.to_json %>"></div>

<div>
  <%= link_to "Back to schedules", schedules_path if current_user.role == "admin"%>
</div>
	
<div id="ec"></div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@event-calendar/build@1.5.0/event-calendar.min.css">
<script src="https://cdn.jsdelivr.net/npm/@event-calendar/build@1.5.0/event-calendar.min.js"></script>
<%= javascript_include_tag 'calendar' %>