config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :deliveries
  resources :availabilities
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  get '/users/fetch_users', to: 'users#fetch_users'
  resources :users
  resources :branches do
    get :join_company, on: :collection
  end
  resources :companies
  #resources :articles

  devise_scope :user do
    get 'choose_branch', to: 'devise/sessions#choose_branch'
  end

  root "home#home"

  get '/dashboard', to: 'dashboard#index', as: 'user_dashboard'
  get 'join_company', to: 'companies#join'

  get 'join_request/:company_id', to: 'companies#join_request', as: 'join_request'
  get 'join_now/:company_id', to: 'companies#join_now', as: 'join_now'

  get 'select_branch/:branch_id', to: 'branches#select_branch', as: 'select_branch'

  get '/contact', to: 'contact_customer#show_form', as: 'contact_form'
  post '/contact', to: 'contact_customer#send_email', as: 'send_contact'
end

app/models/company.rb
class Company < ApplicationRecord
has_many :branches, dependent: :destroy
has_many :company_opening_hours, dependent: :destroy
accepts_nested_attributes_for :company_opening_hours
validates_associated :company_opening_hours
validates :name, :company_iden, presence: true

has_many :users, through: :branches
has_many :availabilities, through: :users
has_many :schedules, through: :users
has_many :branch_schedules, through: :branches, source: :schedules


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_admin_role, only: [:edit, :update, :destroy]

  # GET /companies or /companies.json
  def index
    @companies = Company.joins(:branches).where(branches: { id: current_user.branch_id })
  end

  # GET /companies/1 or /companies/1.json
  def show
    @company = Company.find(params[:id])

    # Allow showing the company if it's associated with the current user's company
    # OR if the current user is an admin and the company is associated with the user's company_id.
    if (@company.id == current_user.branch.company.id) || (current_user.role == "admin" && @company.id == current_user..branch.company.id)
      render :show
    else
      redirect_to root_path, alert: "You do not have permission to access this page."
    end
  end

  # GET /companies/new
  def new
    unless (current_user.role == "admin")
        redirect_to root_path, alert: "You do not have permission to access this page."
    end

    @company = Company.new
    initialize_company_opening_hours
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    unless (current_user.role == "admin")
        redirect_to root_path, alert: "You do not have permission to access this page."
    end

    respond_to do |format|
      if @company.save
        create_default_branch_and_update_user_branch
        format.html { redirect_to user_dashboard_url, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        update_user_branch
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def join
    # Code to display a form for the user to enter a company code
    @companies = Company.all
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
        params.require(:company).permit(:name, :company_iden, company_opening_hours_attributes: %i[id day_of_week open_time close_time])
    end

    def initialize_company_opening_hours
        CompanyOpeningHour.day_of_weeks.each do |day_of_week, _index|
            @company.company_opening_hours.build(day_of_week: day_of_week)
        end
    end

    def create_default_branch_and_update_user_branch
        branch = @company.branches.create(name: "New Branch")
        current_user.update(branch_id: branch.id) if current_user
     end

    def update_user_branch
        current_user.update(branch_id: params[:company][:branch_id]) if params[:company][:branch_id] && current_user
    end

    def check_admin_role
        unless (current_user.role == "admin" && @company.id == current_user.branch.company.id)
          redirect_to root_path, alert: "You do not have permission to access this page."
        end
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p>
    <strong>Name:</strong>
    <%= company.name %>
  </p>

  <p>
    <strong>Company ID:</strong>
    <%= company.company_iden %>
  </p>

</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
    <% if company.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

        <ul>
          <% company.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, class: "form-label", style: "display: block" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :company_iden, class: "form-label", style: "display: block" %>
      <%= form.text_field :company_iden, class: "form-control" %>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Day</th>
          <th>Open Time</th>
          <th>Close Time</th>
        </tr>
      </thead>
      <tbody>
        <% CompanyOpeningHour.day_of_weeks.each do |day_of_week, _index| %>
          <%= form.fields_for :company_opening_hours, company.company_opening_hours.find_or_initialize_by(day_of_week: day_of_week) do |opening_hour_form| %>
            <%= opening_hour_form.hidden_field :day_of_week, value: day_of_week.to_s %>
                <tr>
                  <td><%= day_of_week.titleize %></td>
                  <td>
                    <%= opening_hour_form.time_select :open_time, { class: "form-control", default: Time.new(2000, 1, 1, 9, 0, 0) } %>
                  </td>
                  <td>
                    <%= opening_hour_form.time_select :close_time, { class: "form-control", default: Time.new(2000, 1, 1, 17, 0, 0) } %>
                  </td>
                </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Show this company", @company %> |
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Company</h1>
<% if current_user.role == 'admin' %>
	<%= link_to "New company", new_company_path if current_user.role == "admin"%>
	<br></br>
<% end %>


<div id="companies">
  <% @companies.each do |company| %>
    <%= render company %>
    <p>
		<%= link_to "Show this company", company, class: "btn btn-primary btn-sm" if current_user.role == "admin"%>
	</p>
  <% end %>
</div>

app/views/companies/join.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-4">
    <h1>Join a company</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @companies.each do |company| %>
                <tr>
                    <td>
                        <%= company.name %>
                    </td>
                    <td>
                        <%= link_to "Join and View Branches", join_company_branches_path(company_id: company.id), class: "btn btn-primary" %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>
<% if current_user&.branch&.company&.id %>
	<strong>Creating a new company will remove all access and associations that exist with your current company!</strong>
<% end %>
<%= render "form", company: @company %>

<br>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>
	
<div class="d-flex justify-content-between align-items-center">
  <%= link_to "Edit this company", edit_company_path(@company), class: "btn btn-primary" if current_user.role == "admin"%>
  <%= link_to "Back to companies", companies_path, class: "btn btn-secondary" %>
  <%= button_to "Destroy this company", @company, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", form: { class: "d-inline" } if current_user.role == "admin"%>
  
</div>
<div class="text-center">
	<br></br>
	<% if current_user.role == 'admin' %>
	  <p>Warning: Destroying this company will delete all associated branches, users and deliveries!</p>
	<% end %>
</div>